### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by hjian42** [glnmario/cwr4lsc#1]
I read your paper. This is terrific. Do you mind updating the README.md file such to show the steps on how to use your code to reproduce the results? Thanks a lot.

**Comment by glnmario** [comment]
Thanks! I plan to update the readme but in the meantime I'd suggest you look at the [semeval2020](https://github.com/akutuzov/semeval2020) repository with updated code for change detection on multiple languages and with multiple language models. The readme there should help you with reproducing the experiments.

**Comment by hjian42** [comment]
Thanks for pointing me to the shared task repo! This is very helpful! 
Looking to see your updates on README!
